apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
  name: etcd-k8s
  namespace: kube-system
spec:
  ports:
  - name: port
    port: 2379
    protocol: TCP
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 192.168.1.23
    nodeName: etcd-master
  #- ip: 22.22.3.232
  #  nodeName: etcd02
  #- ip: 22.22.3.233
  #  nodeName: etcd03
  ports:
  - name: port
    port: 2379
    protocol: TCP
