apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: metrics-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-app
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second # http_requests_qps
      target:
        type: AverageValue
        averageValue: 800m # 800m 即0.8个/秒，如果是阀值设置为每秒10个，这里的值就应该填写10000m， 不写单位m就是个数
