apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: container-volume-rules
  namespace: monitoring
spec:
  groups:
  - name: volume.rules
    rules:
    - alert: PersistentVolumeClaimLost
      expr: |
         sum by(namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{phase="Lost"}) == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "PersistentVolumeClaim {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is lost\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: PersistentVolumeClaimPendig
      expr: |
         sum by(namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{phase="Pendig"}) == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "PersistentVolumeClaim {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is pendig\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: PersistentVolume Failed
      expr: |
         sum(kube_persistentvolume_status_phase{phase="Failed",job="kube-state-metrics"}) by (persistentvolume) == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Persistent volume is failed state\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: PersistentVolume Pending
      expr: |
         sum(kube_persistentvolume_status_phase{phase="Pending",job="kube-state-metrics"}) by (persistentvolume) == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Persistent volume is pending state\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
