apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: outside-node-exporter
  namespace: monitoring
  labels:
      k8s-app: outside-node-exporter
spec:
  jobLabel: k8s-app
  selector:
      matchLabels:
          k8s-app: outside-node-exporter
      namespaceSelector:
          matchNames:
          - monitoring
  endpoints:
  - port: http
    interval: 10s
    honorLabels: true
    scheme: http
    
