apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: outside-node-exporter
  name: outside-node-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: http
  selector:
    k8s-app: outside-node-exporter
  sessionAffinity: None
  type: ClusterIP
