apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: log
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5040
    nodePort: 30040
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: log
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      nodeSelector:
        kubernetes.io/hostname: node5
      containers:
      - name: logstash
        image: logstash:7.10.1
        ports:
        - containerPort: 9600
        - containerPort: 5040
        resources:
          limits:
            cpu: 3000m
            memory: 4000Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
          - name: config
            mountPath: /usr/share/logstash/config/jvm.options
            subPath: jvm.options
          - name: config
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: pipeline
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
          - key: jvm.options
            path: jvm.options
      - name: pipeline
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf
