---
apiVersion: v1
kind: Service
metadata:
  name: head
  namespace: log
  labels:
    app: head
spec:
  selector:
    app: head
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: head
  namespace: log
  labels:
    app: head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: head
  template:
    metadata:
      labels:
        app: head
    spec:
      containers:
      - name: head
        image: mobz/elasticsearch-head:5
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9100
